version: '2.1'

services:

  nginx:
    image: nginx:${NGINX_PROXY_TAG}
    container_name: nginx
    ports:
      - '${NGINX_PROXY_HTTP}:80'
      - '${NGINX_PROXY_HTTPS}:443'
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
      - ./custom.conf:/etc/nginx/conf.d/custom.conf:ro
    restart: always

  dockergen:
    image: jwilder/docker-gen:${DOCKER_GEN_TAG}
    container_name: nginx-gen
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
    command: -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    depends_on:
      - nginx
    restart: always

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion:${LETSENCRYPT_TAG}
    container_name: nginx-letsencrypt
    environment:
      NGINX_PROXY_CONTAINER: nginx
      NGINX_DOCKER_GEN_CONTAINER: nginx-gen
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - nginx
      - dockergen
    restart: always

volumes:
  conf:
  vhost:
  html:
  certs:

networks:
  default:
    external:
      name: ${NGINX_PROXY_NET}
