version: '2.1'

services:

  whoami:
    image: jwilder/whoami
    container_name: whoami
    environment:
      - VIRTUAL_HOST=whoami.local

networks:
  default:
    external:
      name: ${NGINX_PROXY_NET}
