version: '2.1'

services:

  whoami:
    image: jwilder/whoami
    container_name: whoami
    environment:
      - VIRTUAL_HOST=whoami.${NGINX_HOSTNAME}
      - LETSENCRYPT_HOST=whoami.${NGINX_HOSTNAME}
      - LETSENCRYPT_EMAIL=whoami@no-reply.com

networks:
  default:
    external:
      name: ${NGINX_PROXY_NET}
